version: '2'

services:

    web:
        image: nginx:1.10
        volumes:
            - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - app

    app:
        build:
            context: ./
            dockerfile: ./docker/app.docker
        volumes:
            - ./:/var/www
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_DOCUMENT_DATABASE=0
            - REDIS_DOCUMENT_INDEX_DATABASE=1
        links:
            - redis

    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
        restart: always
